### ISSUE TITLE
good idea -- maybe change the name to WebFuncs.jl

### ISSUE THREAD

**Issue by JeffreySarnoff** [mbesancon/WebFuncs.jl#1]
Most of the newer packages use the plural for the name and the singular for something exported. We cannot name a package the same as we name an e.g. exported type.

This is a good effort.  I hope it goes well.

**Comment by mbesancon** [comment]
Thanks. You're right that's still an idiom I have to get used to, having done some time with Golang mostly.

I'll modify the package name.
